alpha: 0.4
batch_size_test: 32
batch_size_train: 4
bert_config: /workspace/project/ALBEF/configs/config_bert.json
distill: false
image_res: 224
image_root: /workspace/hateful_memes/img
image_root_m: /workspace/multioff/img
image_root_t: /workspace/twitter/dataset_image
optimizer:
  lr: 2e-5
  opt: adamW
  weight_decay: 0.02
schedular:
  cooldown_epochs: 0
  decay_rate: 1
  epochs: 22100
  lr: 2e-5
  min_lr: 1e-6
  sched: cosine
  warmup_epochs: 1
  warmup_lr: 1e-5
test_file_m: /workspace/multioff/ALBEF/test.json
test_file_t: /workspace/twitter/ALBEF/test.json
test_seen_file: /workspace/hateful_memes/ALBEF/test_seen.json
test_unseen_file: /workspace/hateful_memes/ALBEF/test_unseen.json
train_file: /workspace/hateful_memes/ALBEF/train.json
train_file_m: /workspace/multioff/ALBEF/train.json
train_file_t: /workspace/twitter/ALBEF/train.json
val_file_m: /workspace/multioff/ALBEF/val.json
val_file_t: /workspace/twitter/ALBEF/val.json
val_seen_file: /workspace/hateful_memes/ALBEF/dev_seen.json
val_unseen_file: /workspace/hateful_memes/ALBEF/dev_unseen.json
warm_up: false
